name: CI Pipeline - INPE

on:
  push:
    branches: [main, feature/aula08-badges]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Dependencias
        run: npm install

      - name: Executar Testes e Gerar Relatorio
        run: npm run test:coverage

      - name: Enviar Relatorios ao Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
